# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CornellChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CornellChat
  pod 'Alamofire'
  pod 'Google/SignIn'
  pod 'IGListKit'
  pod 'Presentr'
  pod 'SwiftLint'
  pod 'ViewAnimator'
  pod 'lottie-ios'
  pod 'Hero'
end
